### ISSUE TITLE
Implement Moment.js where time is displayed

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#1]
The time-left in a phase of for example a Resolution are currently static.

Please include [moment.js](http://momentjs.com/) (or comparable) to have a live-countdown.

**Comment by kvdmolen** [comment]
- Index page: https://www.dropbox.com/s/hemwr120deq77nb/Screenshot%202015-04-08%2019.18.41.png?dl=0
- Issue page: https://www.dropbox.com/s/pd03qzg12dabirz/Screenshot%202015-04-08%2019.19.07.png?dl=0
- Initiative page (same section)

**Comment by nktc** [comment]
This is done. I implemented this using:
http://hilios.github.io/jQuery.countdown/

To do this I had to create a model field:

```
  selector:add_field("to_char(created+admission_time, 'YYYY-MM-DD HH24:MI:SS')", "end_time")
```

It would be good if you could verify that `created+admission_time` is the correct end date.
