### ISSUE TITLE
Move Sidebar element

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#10]
Move sidebar element "phase" ( 1st on this page: http://dev.liquidfeedback.org/lf3/issue/show/54.html) to the `.main`  - `.section` (first item).

This

``` html
<div class="sidebarSection tab-whatcanido">...</div>
```

Moves to

``` html
<div class="main_outer">
  <div class="main">
    <div class="section">
      ..here..
```

Please update the classname to something like `phases`

Goal is to show something like this:

![image](https://cloud.githubusercontent.com/assets/2168968/7051411/7c4de3ba-de28-11e4-8158-9eca305db46d.png)

So if possible also add some extra, descriptive classnames.

Most important an `.active` class for active phase!

**Comment by nktc** [comment]
Added the active class ... rearranging the site structure is a big job, not ready to make those big changes yet.

**Comment by ghost** [comment]
Ok clear, but the html changes (also in the other issues) are doable?
That's already very helpful.

This particular issue can be done with css too. Please also identify this
sidebar-section with a class e.g. phases

Tnx

On Thursday, April 9, 2015, nktc notifications@github.com wrote:

> Added the active class ... rearranging the site structure is a big job,
> not ready to make those big changes yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Socioneers/LiquidVoting/issues/10#issuecomment-91275548
> .

## 

---

www.socioneers.com

**Comment by nktc** [comment]
Replacing elements is easy (changing image to span).  However,
restructuring the layout (i.e., changing the nesting and moving blocks of
code around, like the sidebar) is more work.

The site is a mix of HTML and Lua and it's pretty messy and repetitive in
places.  I'm still a bit unclear about how the framework is generating the
layout and will need more time to look at this.

**Comment by kvdmolen** [comment]
Thanks for identifying this! 

Indeed let's not spend too much time on difficult issues, and focus on the others first. After we can re-evaluate layout-changes.

**Comment by nktc** [comment]
Ok.  The main difficulty I'm having is that LF is written in WebMCP, a Lua
framework that I have not seen before and which has very little
documentation.

Therefore, to understand it's inner workings I'm having to read the source
code, which is time-consuming.

**Comment by kvdmolen** [comment]
OK, thanks. I know the people who built LF also built WebMCP.

at some point it might be worth digging into (if you're up for it) but for now let's skip the layout-issues
