### ISSUE TITLE
Remove Timeline view

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#12]
In the index-page, `filter` section, remove the `timeline` button as it is only disturbing.

Then, also remove the entire section where this button is places, as only one button is left:

https://www.dropbox.com/s/ank5ziay5w815n1/Screenshot%202015-04-08%2017.06.27.png?dl=0

**Comment by nktc** [comment]
Done, I think...

**Comment by kvdmolen** [comment]
About the sorting of the issues on the index-page, do you have any clue how they are sorted?

Perhaps this "timeline" view was a better default sorting (now I'm totally confused all the time).

Possible to use that default sorting?

**Comment by nktc** [comment]
There was no sort on the issue index, so it was probably undefined.

I set it to `created DESC`.  Let me know if you want something different.

Same goes for the timeline view.

**Comment by kvdmolen** [comment]
yeah much better, thanks!
