### ISSUE TITLE
Change Application title 

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#18]
Please change the (hard coded) titl of the app `LIQUIDFEEDBACK` to `LIQUIDVOTING`.

And the title of the instance `Liquid Feedback 01` to `Socioneers`

![image](https://cloud.githubusercontent.com/assets/2168968/7051079/e4e03ac0-de25-11e4-91fa-849b0822e337.png)

**Comment by nktc** [comment]
Completed.
