### ISSUE TITLE
Cleanup Breadcrumb HTML

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#19]
Cleanup Breadcrumb HTML:
- Remove `<span class="spacer"> » </span>`
- Replace all `<img>` with class-names (e.g. `.notification` and/or `.supporting`). PS the `<img>` indicates if the viewer is actually for example supporting the issue. So only the class-name is the image is there (and remove image)
- Cleanup redundant `<span>` wrappers
- If possible, replace with `<ul>`
- Remove delegation element and replace with `.delegated` class: `<a href="../../delegation/show.html?issue_id=1" class="delegation_info suspended"></a></span>`

Old HTML:

``` html
<div class="slot_title" id="slot_title">
    <a title="Home" class="home" href="../../index/index.html"><img src="../../static/icons/48/home.png" class="icon24"></a>
    <span class="spacer"> » </span>
    <span>
        <span class="unit">
            <a href="../../unit/show/2.html"><span class="name">Unit 1</span></a>
        </span>
        <span class="spacer"> » </span>
        <span class="area">
            <a href="../../area/show/3.html"><span class="name">Subject 1</span></a>
        </span>
        <span class="spacer"> » </span>
        <span class="issue">
            <a href="../../issue/show/1.html">Test #1</a><img title="you are interested" class="star" src="../../static/icons/48/eye.png" alt="you are interested">
            <a href="../../delegation/show.html?issue_id=1" class="delegation_info suspended"></a>
        </span>
        <span class="initiative">Test111</span>
    </span>
</div>
```

New HTML:

``` html
<div class="slot_title" id="slot_title">
    <ul>
        <li class="home">
            <a href="/index.html"><i class="fa fa-home"></i></a>
        </li>
        <li class="unit">
            <a href="..."><span>Unit</span></a>
        </li>
        <li class="area [notifications]">
            <a href="..."><span>Subject</span></a>
        </li>
        <li class="issue [notifications] [delegated]">
            <a href="..."><span>Test #1</span></a>
        </li>
        <li class="initiative [notifications] [supporting] last">
            <a href="..."><span>Test111</span></a>
        </li>
    </ul>
</div>
```

Preferably also add `.last` to the last `<li>` element.

**Comment by nktc** [comment]
This is mostly done:  I have restructured the HTML to unordered list, and added classes for notification `supporting`, `interested`, and `last`.   Had to move some lua code around for this part.

  However, I'm not sure where to find delegated and notifications.  Any clarification you can provide would be helpful.

http://178.62.254.91/lf/initiative/show/1.html

**Comment by kvdmolen** [comment]
- `notification`: my mistake, that does not appear here
- `delegated`: Look here (login as administrator) http://178.62.254.91/lf/issue/show/1.html?tempstore=6dm5jqc6cl75hs56s5r3xlt5zn this issue is **delegated** (as explained in #34). If possible (if difficult, please skip), add the class `.delegated` to the `<li class="issue">` element when an issue is delegated.

**NEW THINGS**
- could you add class `.active` to the `<li class="home">` when currently in homepage?
  so then it becomes `<li class="home active">` when on homepage
- on the [member](http://178.62.254.91/lf/member/show/7.html) page, the member-name is not wrapped inside a `<li class="last">` element, please do so if possible (not very important).
- on the [member-list](http://178.62.254.91/lf/member/list.html) page, same thing, please wrap "member list" in `<li class="last">`
- here: http://178.62.254.91/lf/area/show/3.html please remove the `<img title="you are subscribed"..>` form the breadcrumb, and place `.subscribed` in the `<li class="area">` **if user is subscribed**.

**Comment by nktc** [comment]
I got everything here except `.subscribed`.  Will revisit that.

**Comment by nktc** [comment]
`.subscribed` done.  Sorry, I had to figure out how to get the area delegation info from inside another file.
