### ISSUE TITLE
Remove all JS and HTML for responsive

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#22]
Site will become responsive with pure CSS!

Remove:
- `#swiper_tabs`
- `#swiper_info`
- `#swiper`
- The `function initSlider () {` which is located directly in the HTML

I think also the `showTab()` function is related to the mobile-version, if so can be removed

And perhaps other stuff as well..

**Comment by nktc** [comment]
I removed `#swiper_tabs`, `#swiper_info`, and `#swiper` (ids).  Assuming you did not want me to also remove `.swiper_*` (classes).  Please let me know if that is an incorrect assumption.

**Comment by kvdmolen** [comment]
Nope, let's get rid of as much as possible.

including (if possible, `<div class="swiper">` seems to remain empty):

``` html
<div class="swiper_tabs" style="display: none;">
<!--    <div><a id="tab-0" href="#" onclick="slider.to(0); return false;"><img src="../../static/icons/16/chart_organisation.png" /></a></div>-->
    <div><a id="tab-0" href="#" onclick="slider.to(0); return false;"><img src="../../static/icons/16/text_list_bullets.png" width="32" height="32" /></a></div>
    <div><a id="tab-1" href="#" onclick="slider.to(1); return false;"><img src="../../static/icons/48/info.png" width="32" height="32" /></a></div>
    <div><a id="tab-2" href="#" onclick="slider.to(2); return false;"><img src="../../static/icons/16/group.png" width="32" height="32" /></a></div>
  </div>

  <div></div>
  <div class="swiper" style="position: absolute; width: 100%;">
    <div id="swiper_wrap" class="swiper_wrap">
    </div>
  </div>
```

I see you commented out the JS, perfect.

**Comment by nktc** [comment]
I removed a few more ids/classes, let me know how it looks.

**Comment by kvdmolen** [comment]
### 1

The lower part of the in-body Javascript can also be removed:

`function resizeHandler() {}` and `$( window ).resize( resizeHandler );resizeHandler();`

So if you ask me just delete the whole `<script>` tag!

### 2

If you can find it, please remove this junk (see source of [index](http://178.62.254.91/lf/)):

``` html
<div style="display: none;">
<!--    <div><a id="tab-0" href="#" onclick="slider.to(0); return false;"><img src="./static/icons/16/chart_organisation.png" /></a></div>-->
    <div><a id="tab-0" href="#" onclick="slider.to(0); return false;"><img src="./static/icons/16/text_list_bullets.png" width="32" height="32" /></a></div>
    <div><a id="tab-1" href="#" onclick="slider.to(1); return false;"><img src="./static/icons/48/info.png" width="32" height="32" /></a></div>
    <div><a id="tab-2" href="#" onclick="slider.to(2); return false;"><img src="./static/icons/16/group.png" width="32" height="32" /></a></div>
  </div>

  <div></div>
  <div style="position: absolute; width: 100%;">
    <div>
    </div>
  </div>
```

### 3

Only after login (on index page) I get this floating `div`, please remove:

``` html
<div>select tabs ↑ or swipe ←<br>
to show more info and learn what you can do
</div>
```

![image](https://cloud.githubusercontent.com/assets/2168968/7113762/3c1d1ab0-e1d7-11e4-8195-8cff649db471.png)

**Comment by nktc** [comment]
All done, I think.
