### ISSUE TITLE
Change HTML for Add/remove interest (issue page)

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#24]
At: http://178.62.254.91/lf/issue/show/2.html

There's a button `add my interest`. Change the Add interest HTML from:

``` html
<div class="right">
  <form ...></form>
  <script type="text/javascript">...</script>
  <a class="btn btn-default" ...>add my interest</a>
</div>
```

to

``` html
<div class="btn-interest">
  <form ...></form>
  <script type="text/javascript">...</script>
  <i class="fa fa-bell-slash"></i><a class="" ...>Add interest</a>
</div>
```

(remove class from `<a>`)

And the Remove interest from:

``` html
<div class="right">
  <img class="icon48 right" src="../../static/icons/48/eye.png">You are interested in this issue<br>
  <form ...></form>
  <script type="text/javascript">...</script>
  <a ...>remove my interest</a>
</div>
```

to

``` html
<div class="btn-interest interested">
  <form ...></form>
  <script type="text/javascript">...</script>
  <i class="fa fa-bell"></i><a ...>Remove interest</a>
</div>
```

**Comment by nktc** [comment]
Added.

However, I think you had the fa-bell classes reversed.  Let me know if that
is not what you intended.

**Comment by kvdmolen** [comment]
Nope, well, that means it's ambiguous. Please make both simply the `fa-bell`. I'll use a color to indicate status.

Also, (same as other remark) `<i>` tag is now a wrapper, but should just be `<i></i>` in front of `<a>` element (see HTML above)

Also, please add class `.interested` to `.btn-interest` when user is interested (see above)

Tnx!

**Comment by nktc** [comment]
Please re-open if not correct.

178.62.254.91/lf/issue/show/1.html
