### ISSUE TITLE
Change default text in <textarea>

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#33]
At http://178.62.254.91/lf/initiative/new.html?area_id=3 and http://178.62.254.91/lf/initiative/new.html?issue_id=1

There is default text in `<textarea>`, please **remove** this default text.

Also, please add a link to this text: 

`Enter your proposal and/or reasons`

so it becomes:

`Enter your proposal and/or reasons (examples)` 

where **examples** is the link to a STATIC page examples.html. Is that possible? I will provide the page, it will contain Markdown help and guidance.

**Comment by nktc** [comment]
Done.
