### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#34]
Difficult one. Idea is that you can delegate your vote to someone else.

Either for one specific issue, or for all issues in one "area".

See (login as administrator): http://178.62.254.91/lf/delegation/show.html?preview_trustee_id=7&tempstore=rn1k5ggw3h4xnb6x43xnnplcwy&issue_id=1 This issue is delegated to kvdmolen.

TODO:
- please remove the arrow img in the sidebar: `<img title="delegated to" class="delegation_arrow delegation_arrow_overridden" src="../static/delegation_arrow_24_vertical.png" alt="delegated to">`
- Please remove `<br ..>` elements anywhere you find them
- Follow the sidebar cleanup things a bit also here, especially add some unique/descriptive classnames: `.sidebarRow` can become `.row .owner` or `.row .delegatee`

**Comment by nktc** [comment]
I think this is done, let me know if you want additional classes added.
