### ISSUE TITLE
Replace <img> in index-page

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#35]
Replace the green thumbs-up image `<img alt="supporter" ..>` with `<i class="fa fa-thumbs-up tooltip"><span><span>{{You are subscribed}}</span></span></i>` (use [text](https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.ka.lua#L978) from translations-file)

``` html
<span class="initiative_name">
  <a href="../initiative/show/17.html">this is the initiative</a>
  <img alt="supporter" src="../static/icons/32/support_satisfied.png" title="supporter" class="icon16">
</span>
```

**Comment by nktc** [comment]
Complete, tested with https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.de.lua#L978.

German is a bit easier on my American eyes :) :)

**Comment by kvdmolen** [comment]
You forgot to add `.tootltip` class to the `<i class="fa fa-thumbs-up">`

Good to see you are in control of the language! Indeed it works nicely :)

**Comment by nktc** [comment]
Added, thanks.

**Comment by kvdmolen** [comment]
My bad, please use the text _("You are supporter") here.. 

https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.ka.lua#L693

**Comment by nktc** [comment]
Added.
