### ISSUE TITLE
Replace another <img> in index-page

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#36]
- Replace `<img alt="you are interested" ..>` with `<i class="fa fa-bell tooltip"><span><span>{{You are interested}}</span></span></i>` (use [text](https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.ka.lua#L977) from translations-file)
- Remove `<img title="delegates to" ..>` (See [here test 1](http://178.62.254.91/lf/index/index.html) when logged in as admin)
- Remove all `<br>`'s you can find
- Remove spaces where possible..

``` html
<div class="issue_context">
  <a href="../unit/show/2.html" class="unit">Unit 1</a>
  <a href="../area/show/3.html" class="area">Subject 1</a>
  <img alt="you are interested" src="../static/icons/48/eye.png" title="you are interested" class="star">
  <br>
  <a href="../delegation/show.html?issue_id=1" class="delegation_info suspended">
    <img title="delegates to" src="../static/delegation_arrow_24_horizontal.png" alt="delegates to" class="delegation_arrow">
    <img title="kvdmolen" src="../member_image/show/7.html?image_type=avatar" class="member_image member_image_avatar micro_avatar">
  </a>
</div>
```

**Comment by nktc** [comment]
Done, I think... let me know?

**Comment by kvdmolen** [comment]
Done!
