### ISSUE TITLE
Remove Trace?

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#4]
`Trace` can be completely removed (from users perspective)

``` html
<div id="trace">...</div>
```

**Comment by nktc** [comment]
Do you want me to remove `id="trace"`, or the entire trace section?

**Comment by kvdmolen** [comment]
Well, if you need it for debugging, perhaps for now leave it.

What I mean is indeed remove entire section (reduces page-load and only for debugging).

**Comment by nktc** [comment]
In the config script I have set:

```
config.enable_debug_trace = false
```

So trace information should not be generated and should not appear.
