### ISSUE TITLE
Remove Search img

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#40]
In header (`.nav`) please remove entire `<a>` (see below) element, as it is a duplicate of hitting `enter` in the searchbox, and does not function as expected: entering text and then clicking the magnifier will not search that text, very annoying..

Please verify `enter` in searchbox with text still works after removing `<a>`!

To be removed:

``` html
<a class="searchLink" href="./index/search.html"><img src="./static/icons/16/magnifier.png"></a>
```

**Comment by nktc** [comment]
Removed; enter still works.
