### ISSUE TITLE
Add class .section-suggest

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#44]
At: http://178.62.254.91/lf/suggestion/new.html?initiative_id=1

Please add `.section-suggest` to (NOTE, here the `.section` is a `form`):

``` html
<form class="section">
 ...
</form>
```

If possible (layout WebMVC framework-wise, please add the Breadcrumb in this page!

**Comment by nktc** [comment]
Added `section-suggest` (though it was `section vertical`).

Added breadcrumb.

**Comment by kvdmolen** [comment]
Cool, looks good
