### ISSUE TITLE
More Breadcrumb li-wrappers

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#47]
Please check these pages for clean `<ul><li>` structure:
- Every text wrapped in `<li>`
- Class `.last` for last
- Remove `.spacer` (one left, member-settings-page)

http://178.62.254.91/lf/suggestion/new.html?initiative_id=1
http://178.62.254.91/lf/admin/index.html
http://178.62.254.91/lf/member/settings_email.html
http://178.62.254.91/lf/member/list.html
http://178.62.254.91/lf/index/search.html?_webmcp_routing.default.mode=forward&_webmcp_csrf_secret=IHu9HDeOuOnhQ6rsh1YPe1k2d63MRkdP&_webmcp_routing.default.view=show&_webmcp_routing.default.module=member&q=test

**Comment by nktc** [comment]
I think I hit them all.  Please let me know if I missed something.

**Comment by kvdmolen** [comment]
More here: http://178.62.254.91/lf/unit/show/2.html :
- Replace `<span>` with `<li>`
- Remove entire `a.delegation_info`
- If `a.delegation_info` exists, add `.delegated` class to `<li>` element

And here: http://178.62.254.91/lf/member/settings_notification.html 
- Please note the "Administrator" is wrapped in `<li>`, but not the "notification settings"
- The **latter** should receive the class `.last`

**Comment by nktc** [comment]
Done.
