### ISSUE TITLE
Add class .section-issue-new

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#48]
Please note these differences when adding new initiative:
- Completely new issue + initiative: http://178.62.254.91/lf/initiative/new.html?area_id=3
- New initiative for **existing** issue: http://178.62.254.91/lf/initiative/new.html?issue_id=1

Is it possible to add class `.section-issue-new` to the **first** one only?

**Comment by nktc** [comment]
Done.
