### ISSUE TITLE
Use Font-awesome

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#5]
Replace all icons (currently often images) with similar font-awesome icons:

At `.nav` section (header):

``` html
<div class="head">
  <div class="nav">
    ...
    <a class="notifications" title="notifications" href="../index/notifications.html"><img alt="notifications" class="icon" src="../static/icons/48/bell.png"><span class="count">1</span></a>
  </div>
</div>
```

to:

``` html
<a class="notifications" title="notifications" href="../index/notifications.html"><i class="fa fa-bell"></i><span class="count">1</span></a>
```

--- there'll be more..

**Comment by nktc** [comment]
Which page does this appear on?  I have made the changes in code but I can't find where it is in the UI to test it...

**Comment by kvdmolen** [comment]
http://dev.liquidfeedback.org/lf3/index/notifications.html but not sure if this page only exists IF there are notifications. Though this Fontawesome thing is for all icons, have not yet listed them all, most are inside another issue (including the breadcrumb home-icon and so).

**Comment by kvdmolen** [comment]
Super!

![image](https://cloud.githubusercontent.com/assets/2168968/7100846/f88d5d0e-e038-11e4-8a7a-b344dbfb022a.png)
