### ISSUE TITLE
Notification Emails

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#51]
Apart from the (english) content, I have actually not yet received any notification-email (though I have set to receive in http://178.62.254.91/lf/member/settings_notification.html)

Do you have any clue on when these emails are sent? Can you check if indeed they are sent?

I don not know exactly how this works, but I think it is parallel to the notification-bell in the UI.

**Comment by nktc** [comment]
I had to start a background script to send these.  You should start
receiving some now, let me know if not.
