### ISSUE TITLE
hard-coded display:none;

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#53]
on initiative page: http://178.62.254.91/lf/initiative/show/1.html

there are two sidebar-tabs that have `display:none` in the style element.

perhaps you forgot to remove, but the `style="display:none;"` can be removed :)

**Comment by nktc** [comment]
Actually it is the random javascript `hide()`s here that are inserting `display: none` into the DOM:

https://github.com/Socioneers/LiquidVoting/blob/master/frontend/app/main/initiative/show.lua#L33

I have removed this JS and the `display:none`s are gone.
