### ISSUE TITLE
replace thumbs-image with i

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#55]
at http://178.62.254.91/lf/initiative/show/1.html

in the sidebar, member-area, please replace the thumbs-up image with:

``` html
<i class="fa fa-thumbs-up tooltip"><span><span>{"supporter"}</span></span></i>
```

text: https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.en.lua#L931

**Comment by nktc** [comment]
Done, please verify.

**Comment by kvdmolen** [comment]
Ah, you can leave this, but I meant the one below, at **Interested members**!

**Comment by nktc** [comment]
OK now?

**Comment by kvdmolen** [comment]
:+1:

**Comment by kvdmolen** [comment]
No, sorry, wrong text, please use simply ("supporter"):

https://github.com/Socioneers/LiquidVoting/blob/master/frontend/locale/translations.en.lua#L931

**Comment by nktc** [comment]
Are we there yet?

http://178.62.254.91/lf/initiative/show/1.html

:)

**Comment by kvdmolen** [comment]
yes! styling = my bad :)
