### ISSUE TITLE
Breadcrumb: wrap some text in <span>

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#56]
At http://178.62.254.91/lf/issue/show/1.html the text "Unit 1" and "subject 1" are wrapped in a `<span>` element (allowing the icon).

At http://178.62.254.91/lf/area/show/3.html and http://178.62.254.91/lf/unit/show/2.html they are not.

Please wrap in `<span>` also there..

**Comment by nktc** [comment]
Done.
