### ISSUE TITLE
New issue (initiative) directly switches to phase 2

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#57]
http://178.62.254.91/lf/issue/show/17.html

Creating a new issue (initiative) directly switches to phase 2, and skips phase 1

create issue: http://178.62.254.91/lf/initiative/new.html?area_id=3

**Comment by nktc** [comment]
Not sure this is a bug, it says:

```
As soon as one initiative of this issue reaches the 1st quorum of 10% support, the issue will proceed to discussion phase
```

And it shows as being 10% when first added:  http://178.62.254.91/lf/initiative/show/25.html

**Comment by kvdmolen** [comment]
Damn, think you're right! With only 4 people registered, one supporter will already make it so..

Ok!
