### ISSUE TITLE
"Email confirmation" Email missing links

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#6]
This is the content of current email for "email confirmation".

The links are missing the URL (and so not working). Let's stick to the IP address for now.

```
Hello Administrator,

Please confirm your email address by clicking the following link:

/lf/index/confirm_notify_email.html?secret=B33T2HF6kZBe96q2BBN2fgyv

If this link is not working, please open following url in your web browser:

/lf/index/confirm_notify_email.html

On that page please enter the confirmation code:

B33T2HF6kZBe96q2BBN2fgyv
```

**Comment by nktc** [comment]
Updated to use server IP.

**Comment by kvdmolen** [comment]
I still got the missing links in the "add member" email:

![image](https://cloud.githubusercontent.com/assets/2168968/7100691/86ece1a4-e030-11e4-95d2-b0409c81894a.png)

**Comment by nktc** [comment]
Okay, code duplication again.  I had changed in in one place but not another.

Note that `model/member.lua` contains a hard-coded secret key, which is potentially dangerous.
