### ISSUE TITLE
Sidebar 3

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#60]
Please add a unique classname on any `<a>` and `<h3>` element you can find.

Simply `.a01`, `.a02` / `.h01`, `.h02`, .. would be fine

It'll allow me to add an icon to a specific button / change colors..

**Comment by nktc** [comment]
Which page is this in reference to?  You can always address a given link using CSS `:nth-child()`.

**Comment by ghost** [comment]
In all pages actually.

The nth child doesn't work because the blocks are different during for
example the various phases. Plus they appear in different ul's

I hoped there is "one" place where these sidebar tabs are generated in the
code? Or am I now asking you to go through 1000 files?

On Monday, April 20, 2015, nktc notifications@github.com wrote:

> Which page is this in reference to? You can always address a given link
> using CSS :nth-child().
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Socioneers/LiquidVoting/issues/60#issuecomment-94507467
> .

## 

---

www.socioneers.com

**Comment by nktc** [comment]
I have done my best to give the links unique class names.  I was working quickly, so please let me know if any issues.

**Comment by nktc** [comment]
```
liquid_feedback_01=> select * from unit
;
 id | parent_id | active |       name        | description | member_count |       text_search_data        
----+-----------+--------+-------------------+-------------+--------------+-------------------------------
  3 |         2 | t      | Unit 1.1          | Child unit  |            5 | '1.1':2 'child':3 'unit':1,4
  1 |           | t      | Political Party 1 |             |            6 | '1':3 'party':2 'political':1
  2 |           | t      | Central District  |             |            6 | 'central':1 'district':2
  4 |           | t      | District East     |             |            3 | 'district':1 'east':2
(4 rows)
```

**Comment by kvdmolen** [comment]
Here are a few left (they all have `.pageview` class):

http://178.62.254.91/lf/member/show/1.html

``` html
<ul class="ul">
  <li><a class="pageview" href="../../member/settings_notification.html">notification settings</a></li>
  <li><a class="pageview" href="../../member/settings_email.html">change your notification email address</a></li>
  <li><a class="pageview" href="../../member/settings_name.html">change your screen name</a></li>
  <li><a class="pageview" href="../../member/settings_login.html">change your login</a></li>
  <li><a class="pageview" href="../../member/settings_password.html">change your password</a></li>
  <li><a class="pageview" href="../../member/developer_settings.html">developer settings</a></li>
</ul>
```

Rest seems all OK! thanks

**Comment by nktc** [comment]
Added a number, let me know if that's not what you want.  Thanks!

**Comment by kvdmolen** [comment]
:+1:
