### ISSUE TITLE
Sidebar 4: remove floating text

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#61]
Please give any "floating" text in the sidebar a unique classname (so i can hide with css) e.g. `.txt01`:
- http://178.62.254.91/lf/initiative/show/20.html (beware, remove `display:none` first #53)
- http://178.62.254.91/lf/area/show/1.html
- http://178.62.254.91/lf/unit/show/1.html
- ...

**Comment by nktc** [comment]
I have added unique classes to the text appearing on these pages, let me know if there are others!

**Comment by kvdmolen** [comment]
some more here, wrapped in li's

http://178.62.254.91/lf/initiative/show/1.html

**Comment by nktc** [comment]
I think I got them all now.

**Comment by kvdmolen** [comment]
two more on initiative page: http://178.62.254.91/lf/initiative/show/26.html (but only in verification-phase!) hope you can find them..

**Comment by nktc** [comment]
I do not see it.  How can I make an issue be in verification phase so I can test this?

**Comment by kvdmolen** [comment]
Created one! A new Policy with a verification-time of 30 days:

http://178.62.254.91/lf/issue/show/26.html
- Additional bug 1: here also the time says "finished" at my computer..
- Additional bug 2: the issue-name was entered in the form, but does not appear here..

pls check :) thanks!

**Comment by nktc** [comment]
- I do not see floating text here.  Are you asking me to remove `display:none`?  Sorry, confused.
- Re. "finished", this date is also in the past so will not count down without changes to the countdown logic.
- There was a bug causing issue name not to be populated in the database.  It should be fixed now.

**Comment by kvdmolen** [comment]
All seems done!
