### ISSUE TITLE
Bargraph: change colors

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#63]
If possible, please change the bar-graph colors:
- Green: #27ae60
- Blue: #34495e (not really blue, but it's simply a line)
- Red: #e74c3c
- Orange: #f39c12

Source: http://flatuicolors.com/

**Comment by nktc** [comment]
There is code duplication here.  I changed it on this page:

http://178.62.254.91/lf/initiative/show/21.html

Please reopen if we need changes in other places.
