### ISSUE TITLE
Remove "a" element

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#67]
At index page http://178.62.254.91/lf/index/index.html

At the delegation-icon (hand) in the blue issue, please remove the `<a>` wrapper around `<i>`

from:

``` html
<a href="../index/">
  <i class="fa fa-hand-o-right tooltip"><span><span>You delegated this issue</span></span></i>
</a>
```

to

``` html
<i class="fa fa-hand-o-right tooltip"><span><span>You delegated this issue</span></span></i>
```

same as notification-icon

**Comment by nktc** [comment]
Complete.

**Comment by kvdmolen** [comment]
The `<i class="fa ..` element now is completely gone!

It was visible on the index page and on issue-page (if issue is delegated) top-right on the blue issue canvas (next to the Bell-icon).

If you can find where it is, please place back :)

**Comment by nktc** [comment]
OK now?
