### ISSUE TITLE
Vote phase error

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#69]
Also mentioned in #21 

Click "vote now" button in sidebar will generate error: http://178.62.254.91/lf/issue/show/23.html

**Comment by nktc** [comment]
I think this is sorted now.  This is due to the following code in the issue model:

`assert(options.member_id, "member_id mandatory for member_info")`

Not really sure why this is being asserted.  I commented it and that voting page works fine now.
