### ISSUE TITLE
Footer static pages

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#73]
1. Where can we find the About page? http://178.62.254.91/lf/index/about.html
2. Where can we find the Usage terms page? http://178.62.254.91/lf/index/usage_terms.html
3. Usage terms page now requires login, this should not be required. If easy, please change?
4. The "LiquidFeedback" link, please remove, and place instead:

``` html
<a href="https://github.com/Socioneers/LiquidVoting" target="_blank">GitHub</a>
```

tnx

**Comment by nktc** [comment]
1. About is generated via:
   https://github.com/Socioneers/LiquidVoting/blob/master/frontend/app/main/index/about.lua and https://github.com/Socioneers/LiquidVoting/blob/master/frontend/config/example.lua
2. Terms generated via:
   https://github.com/Socioneers/LiquidVoting/blob/master/frontend/app/main/index/about.lua and https://github.com/Socioneers/LiquidVoting/blob/master/frontend/app/main/index/usage_terms.lua
3. Done.
4. Done.
