### ISSUE TITLE
.section class duplications

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#75]
Since some time, I see many `.section` classes as **child** of the "root" `.section`

For example here: http://178.62.254.91/lf/index/notifications.html

``` html
<div class="section">
  <div class="sectionHead">
    <h1>Notifications</h1>
  </div>
  <div class="section row">
    <ul class="ul">
      ..
```

Probably collateral damage. If you have a clue on how to remove the **child** `.section` classes, please do so (see it at many, maybe all pages, often with `.row`)

I can make specific css, but already found some issues there.. long story..

If difficult, please skip!

**Comment by nktc** [comment]
Done.
